Bibliomat.WebApp/Models/Shared/BaseViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bibliomat.WebApp.Models.Shared
{
    public class BaseViewModel
    {
        public string ErrorMessage { get; set; }
        public string SuccessMessage { get; set; }
    }
}

Bibliomat.WebApp/Models/Shared/BookViewModel.cs
namespace Bibliomat.WebApp.Models
{
    public class BookViewModel
    {
        public int Id             { get; set; }
        public string Title       { get; set; }
        public string Description { get; set; }
        public int? UserId        { get; set; }
    }
}

Bibliomat.WebApp/Models/Shared/ErrorViewModel.cs
using System;

namespace Bibliomat.WebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Bibliomat.WebApp/Controllers/AuthorizationController.cs
using Bibliomat.BusinessLogic.Abstract;
using Bibliomat.WebApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Bibliomat.WebApp.Controllers
{
    public class AuthorizationController : Controller
    {
        #region Instance Varaibles

        private readonly IUserBusinessLogic _userBusinessLogic;

        #endregion

        #region Constructor

        public AuthorizationController(IUserBusinessLogic userBusinessLogic)
        {
            _userBusinessLogic = userBusinessLogic;
        }

        #endregion

        #region Actions

        /// <summary>
        /// Prepares and passes the needed data for the login-page.
        /// </summary>
        /// <param name="logInViewModel">The ViewModel for the login-page.</param>
        /// <returns>The login-view.</returns>
        [HttpGet]
        public IActionResult Index(LogInViewModel logInViewModel)
        {
            return View(prepareLogInViewModel(logInViewModel));
        }

        /// <summary>
        /// Prepares and passes the needed data for the registration-page.
        /// </summary>
        /// <param name="registerViewModel">The ViewModel for the registration-page.</param>
        /// <returns>The registration-view.</returns>
        [HttpGet]
        public IActionResult Register(RegisterViewModel registerViewModel)
        {
            return View(prepareRegisterViewModel(registerViewModel));
        }

        /// <summary>
        /// Logs the User in.
        /// </summary>
        /// <param name="logInViewModel">The ViewModel for the login-page.</param>
        /// <returns>The Homepage-view if the login was successful or the login-view with an Errormessage if not.</returns>
        [HttpPost]
        public IActionResult DoLogIn(LogInViewModel logInViewModel)
        {
            // Get the Id of the User
            var userId =_userBusinessLogic.LogIn(logInViewModel.Name, logInViewModel.Pass);

            // Check if the login failed
            if (userId == null)
            {
                return View("Index", new LogInViewModel()
                {
                    ErrorMessage = "Incorrect username or password"
                });
            }

            // Create new Session
            HttpContext.Session.SetInt32("UserId", (int)userId);

            // Pass the success-message through the TempData, because the model cannot be passed
            TempData["SuccessMessage"] = "Successfully logged in";

            return RedirectToAction("Index", "Home");
        }

        /// <summary>
        /// Registers the User.
        /// </summary>
        /// <param name="registerViewModel">The ViewModel for the registration-page.</param>
        /// <returns>The Homepage-view if the registration was successful or the registration-view with an Errormessage if not.</returns>
        [HttpPost]
        public IActionResult DoRegister(RegisterViewModel registerViewModel)
        {
            // Declare some easier to use variables
            var name = registerViewModel.Name;
            var pass = registerViewModel.Pass;

            // Try to register the User
            if (_userBusinessLogic.Register(name, pass))
            {
                // Log in
                var userId = _userBusinessLogic.LogIn(name, pass);

                // Create new Session
                HttpContext.Session.SetInt32("UserId", (int)userId);

                // Pass the success-message through the TempData, because the model cannot be passed
                TempData["SuccessMessage"] = "Successfully registered and logged in";

                return RedirectToAction("Index", "Home");
            }

            return View("Register", new RegisterViewModel()
            {
                ErrorMessage = "Username is already taken"
            });
        }

        /// <summary>
        /// Logs the User out.
        /// </summary>
        /// <returns>The Homepage-view.</returns>
        [HttpGet]
        public IActionResult LogOut()
        {
            // Destroy the Session
            HttpContext.Session.Clear();

            // Pass the success-message through the TempData, because the model cannot be passed
            TempData["SuccessMessage"] = "Successfully logged out";

            return RedirectToAction("Index", "Home");
        }

        #endregion

        #region Private Methods

        /// <summary>
        /// Prepares the LoginViewModel.
        /// </summary>
        /// <param name="logInViewModel">The ViewModel for the login-page.</param>
        /// <returns>The prepared LoginViewModel.</returns>
        private LogInViewModel prepareLogInViewModel(LogInViewModel logInViewModel)
        {
            // Create a new LoginViewModel if it does not exist already
            if (logInViewModel == null)
            {
                return new LogInViewModel();
            }

            return logInViewModel;
        }

        /// <summary>
        /// Prepares the RegisterViewModel.
        /// </summary>
        /// <param name="registerViewModel">The ViewModel for the registration-page.</param>
        /// <returns>The prepared RegisterViewModel.</returns>
        private RegisterViewModel prepareRegisterViewModel(RegisterViewModel registerViewModel)
        {
            // Create a new RegisterViewModel if it does not exist already
            if (registerViewModel == null)
            {
                return new RegisterViewModel();
            }

            return registerViewModel;
        }

        #endregion
    }
}

Bibliomat.WebApp/Controllers/CollectionController.cs
using Bibliomat.BusinessLogic.Abstract;
using Bibliomat.Common.Model;
using Bibliomat.WebApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace Bibliomat.WebApp.Controllers
{
    public class CollectionController : Controller
    {
        #region Instance Variables

        private readonly IBookBusinessLogic _bookBusinessLogic;

        #endregion

        #region Constructor

        public CollectionController(IBookBusinessLogic bookBusinessLogic)
        {
            _bookBusinessLogic = bookBusinessLogic;
        }

        #endregion

        #region Actions

        /// <summary>
        /// Prepares and passes the needed data for the your-books-page.
        /// </summary>
        /// <returns>The collection-view.</returns>
        [HttpGet]
        public IActionResult Index()
        {
            return View(prepareCollectionViewModel());
        }

        /// <summary>
        /// Returns a Book.
        /// </summary>
        /// <param name="bookId">The Id of the Book to be retourned.</param>
        /// <returns>The collection-view.</returns>
        [HttpGet]
        public IActionResult Return([FromQuery] int bookId)
        {
            // Check if the User is logged in
            if (HttpContext.Session.GetInt32("UserId") == null)
            {
                // Pass the error-message through the TempData, because the model cannot be passed
                TempData["ErrorMessage"] = $"It seems you are not logged in";

                return RedirectToAction("Index", "Home");
            }

            // Get the Book from the passed bookId
            var book = _bookBusinessLogic.GetBook(bookId);

            // Check if the Book exists
            if (book != null)
            {
                // Check if the currently logged in User is the owner of the book
                if (book.UserId == HttpContext.Session.GetInt32("UserId"))
                {
                    // Try to return the book
                    var returnSuccessful = _bookBusinessLogic.ReturnBook(bookId);

                    // Check if the book has been returned successfully
                    if (returnSuccessful)
                    {
                        // Pass the success-message through the TempData, because the model cannot be passed
                        TempData["Successmessage"] = $"The book has been returned";

                        return View("Index", prepareCollectionViewModel());
                    }

                    // Pass the error-message through the TempData, because the model cannot be passed
                    TempData["ErrorMessage"] = $"The book \"{book.Title}\" could not be returned";

                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    // Pass the error-message through the TempData, because the model cannot be passed
                    TempData["ErrorMessage"] = $"You do not own the book \"{book.Title}\"";

                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                // Pass the error-message through the TempData, because the model cannot be passed
                TempData["ErrorMessage"] = $"The book with id {bookId} does not exist";

                return RedirectToAction("Index", "Home");
            }
        }

        #endregion

        #region Privare Methods

        /// <summary>
        /// Prepares the CollectionViewModel.
        /// </summary>
        /// <returns>The prepared CollectionViewModel.</returns>
        private CollectionViewModel prepareCollectionViewModel()
        {
            // Get all Books of the currently logged in User
            var books = _bookBusinessLogic.GetBooksByUserId((int)HttpContext.Session.GetInt32("UserId"));

            // Create a List of BookViewModels
            var booksForViewModel = new List<BookViewModel>();

            // Fill the List with the gotten Books
            foreach (var book in books)
            {
                var bookForViewModel = new BookViewModel()
                {
                    Id = book.Id,
                    Title = book.Title,
                    UserId = book.UserId
                };

                booksForViewModel.Add(bookForViewModel);
            }

            // Get error- and success-messages if there are any
            var successMessage = TempData["SuccessMessage"];
            var errorMessage = TempData["ErrorMessage"];

            // Create a new CollectionViewModel with all previously set values
            return new CollectionViewModel() {
                Books = booksForViewModel,
                SuccessMessage = (string)successMessage,
                ErrorMessage = (string)errorMessage
            };
        }

        #endregion
    }
}

Bibliomat.WebApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bibliomat</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bibliomat</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @{
                            if (Context.Session.GetInt32("UserId") != null)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Collection" asp-action="Index">Your Books</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Authorization" asp-action="LogOut">Log Out</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Authorization" asp-action="Index">Log In</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Authorization" asp-action="Register">Register</a>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Bibliomat - Matthias Bächler
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>